0.1.7
mozilla-services/iprepd-nginx pull request #21
Opened 2019-01-15 21:53 UTC by ajvb

* Replace `dont_block` variable with the less confusing `blocking_mode`. Also makes it off by default.
* Remove early return so that `iprepd.status.accepted` is always set when a request is not blocked.
* Gather new metric for total calls to iprepd's get reputation endpoint (`iprepd.get_reputation`)

cc: @milescrabill - Will need to swap the "blocking enabled" variables in cloudops-infra back to what you had them at :)

2019-01-15 22:54 UTC, ameihm0912 approved these changes

2019-01-17 18:25 UTC, milescrabill requested changes

2019-01-17 18:25 UTC, milescrabill commented on lib/resty/iprepd.lua
> +          if string.find(err, "could not be resolved") and string.find(err, "Operation timed out") then
We should log the `else` condition cases (errors with spaces in them that are not DNS or timeouts)

2019-01-17 18:31 UTC, milescrabill approved these changes

2019-01-17 18:33 UTC, merged